language: ruby
dist: xenial
bundler_args: "--without deployment"
sudo: required
services: mysql
addons:
  chrome: stable
  apt:
    packages:
    - haveged
    - google-chrome-stable
cache:
  bundler: true
env:
  global:
  - TZ=Europe/London
  - DISPLAY=:99.0
before_script:
- bundle exec rake db:setup
- bundle exec rake webdrivers:chromedriver:update
script:
- xvfb-run -a bundle exec rspec
before_deploy: "./compile-build"
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: radome/sm_workflow_lims
  api_key:
    secure: RZRxB/PjhNiy+hXsVvGqM/BW1lnLQRYGInXHC7XavDV5WyPbS44+PeUQJhy2/4+rEc76RlGqnDnLX9WytVtV9zkCtOkesW9OuHDV3ohsKmfXprSCR5nz+/PDT3I07d7x87ChPgi5Cdovj+K8Q5oJ9pH3h4KB0ugeAeqCtrUT64zqJE/MOlZrR+VwUS6uaRsOa49x2NGbLo6EEVdJ/uN/iU+d9hsfs4l0d4TEIQR4N0UeHzHUu8VWTPkyZzCk0XteR9BikT+8ARSbB71czy53HDIL0n5WUTTKe4GpP20JKV7JE/bJ2HOtDyXsC9hQ7CQ4ViFz488S2liiHfE+LUm+dGEvA1kw3WSAer4dD5vpOcsIPlDgPXW095JfSK3sO3Yh9sMfYg5z5h5eO2xyjKZTMBw5RrNE7js5ABjWKHxuVVtkAIuv5NPpyXQdt07S/ySgyNC+3x3cDm7p0osS8CxkZU/E4/D1gzXCGmBPgfDXkrNA9nYe85qsuDDTBawk2MEfRprAzNu4ht0umoQDpjJ5Ev0pXD+RikZxgGAH+1jMmfFvlPvAum5a52KO8aOL6ndohVykmgjsUKy+kO7NUrsAnyTTlNnsCLOuP8Myd5FFDxleduRWRcv5JxmsN/KoT7RBraueoUKYUpTfujenNmSIVIsbP4upDoExdSe1A4h1OYE=
