language: ruby
dist: xenial
bundler_args: "--without deployment"
sudo: required
services: mysql
addons:
  chrome: stable
  apt:
    packages:
    - haveged
    - google-chrome-stable
cache:
  bundler: true
env:
  global:
  - TZ=Europe/London
  - DISPLAY=:99.0
before_script:
- bundle exec rake db:setup
- bundle exec rake webdrivers:chromedriver:update
script:
- xvfb-run -a bundle exec rspec
before_deploy: "./compile-build"
deploy:
  provider: releases
  file: release.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: sanger/sm_workflow_lims
  api_key:
    secure: HfqMocrfgmbGqiRbVoXQDhsfK2bB0+yjksZW1G+hvAEE3eHVbMbQntorkuC9tkW5uat3Qpw5RvS/78gFopS4nonPQZUQkM5dWZmLxSRHK1bATJV7MAfZuCnjGFODlxPhykTvfW4S37lhYxNLRSZzmERxvQs8rljKCuUSxjC/EsM=
